# Generated by Django 4.2.7 on 2024-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
